### 获取验证码
GET http://localhost:8080/generate/captcha

### 表单注册

POST http://localhost:8080/register
Content-Type: multipart/form-data; boundary=WebAppBoundary


--WebAppBoundary
Content-Disposition: form-data; name="username"
Content-Type: text/plain

test
--WebAppBoundary
Content-Disposition: form-data; name="password"
Content-Type: text/plain

123456

--WebAppBoundary
Content-Disposition: form-data; name="captchaId"
Content-Type: text/plain

superkey

--WebAppBoundary
Content-Disposition: form-data; name="captcha"
Content-Type: text/plain

super