### 发送邮箱认证码
GET localhost:8080/user/auth/role?email=12110919@mail.sustech.edu.cn

### 认证角色

POST localhost:8080/user/auth/role
Content-Type: multipart/form-data; boundary=WebAppBoundary


--WebAppBoundary
Content-Disposition: form-data; name="code"
Content-Type: text/plain

123456
--WebAppBoundary
Content-Disposition: form-data; name="role"
Content-Type: text/plain

ROLE_STUDENT